### ISSUE TITLE
Nightly prohibits duplicate imports to the prelude

### ISSUE THREAD

**Issue by djmitche** [google/serde_json_lenient#19]
Lots of errors like
```
warning: the item `ToOwned` is imported redundantly
 --> src/value/ser.rs:4:5
  |
4 | use alloc::borrow::ToOwned;
  |     ^^^^^^^^^^^^^^^^^^^^^^
 --> /rustc/3406ada96f8e16e49e947a91db3eba0db45245fa/library/std/src/prelude/mod.rs:125:13
  |
  = note: the item `ToOwned` is already defined here
```
  
These can be reproduced with
```
RUSTFLAGS=-Dwarnings cargo +nightly check --locked
```

I assume these uses are specifically addressing `alloc`, and not `std`. I'm not sure what the best fix is -- can we assume they arei n the prelude, or will that fail in nostd builds?

**Comment by adetaylor** [comment]
My previous attempt at fixing these was by merging in the latest `serde_json` code which usually fixes these things, but on this occasion didn't work. We should try that again rather than trying to fix this in `serde_json_lenient`, and if that doesn't work we should figure out what's different between `serde_json` and `serde_json_lenient` here.

I am incentivized to fix this because I get an angry email from github about it every day, but so far haven't had time to try again.

**Comment by adetaylor** [comment]
I just rolled to upstream again, and hopefully it's fixed it. (Due to Google's CLA bot, upstream rolls need to be pushed directly to `main`, so there's no PR for this).

**Comment by adetaylor** [comment]
This appears to be fixed.
